### ISSUE TITLE
Failed to compile when running web:prod:serve

### ISSUE THREAD

**Issue by soyosef** [tamagui/starter-free#34]
For a fresh template created with `npm create tamagui@latest`. When trying `web:prod:serve`, it outputs an error:

`Failed to compile.
TypeError: Cannot read properties of undefined (reading 'length')
    at simpleHash (/Users/yos/git/code/js/tamagui/hello/node_modules/@tamagui/simple-hash/dist/cjs/index.js:24:19)
    at createCSSVariable (/Users/yos/git/code/js/tamagui/hello/node_modules/@tamagui/static/node_modules/@tamagui/web/dist/cjs/createVariable.js:77:46)
    at variableToCSS (/Users/yos/git/code/js/tamagui/hello/node_modules/@tamagui/static/node_modules/@tamagui/web/dist/cjs/helpers/registerCSSVariable.js:25:139)
    at /Users/yos/git/code/js/tamagui/hello/node_modules/@tamagui/static/node_modules/@tamagui/web/dist/cjs/createTamagui.js:68:162
    at createTamagui (/Users/yos/git/code/js/tamagui/hello/node_modules/@tamagui/static/node_modules/@tamagui/web/dist/cjs/createTamagui.js:108:5)
    at loadTamagui (/Users/yos/git/code/js/tamagui/hello/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:51:116)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/yos/git/code/js/tamagui/hello/node_modules/tamagui-loader/dist/cjs/TamaguiPlugin.js:107:7`

Already tried `npm run build` at the root before the web build but it didnt help.

**Comment by soyosef** [comment]
Tried again today after the last commit with updated versions of tamagui and @tamagui/next-plugin. There was a different error but deleting the next/pages directory did the trick, and is now working.
